### ISSUE TITLE
[Relatório Técnico] - Criação de uma seção para o relatório técnico

### ISSUE THREAD

**Issue by ademarsj** [dcc-ufla/guia-do-tcc#10]
Como uma alternativa também para os custos de Sistemas de Informação e Ciência da Computação para as grades anteriores à 2022 seria bom ter algumas especificações de como o trabalho pode ocorrer uma vez que não se encontra facilmente essa informação nos documentos da UFLA.

**Comment by paulojunior-ufla** [comment]
Olá @ademarsj. Sua contribuição é muito bem-vinda. Irei analisá-la o quanto antes...
