### ISSUE TITLE
Resolver PR pendentes

### ISSUE THREAD

**Issue by paulojunior-ufla** [dcc-ufla/guia-do-tcc#12]
Realizar as modificações sugeridas pelo mantenedor nos PR #7 e #9 e submeter um novo PR. Citar os autores dos PR originais no novo PR.

**Comment by ademarsj** [comment]
@paulojunior-ufla , realizei um novo PR (#13) com os ajustes solicitados nos dois PR´s mencionados.

**Comment by paulojunior-ufla** [comment]
Olá, @ademarsj. Obrigado por sua contribuição mais uma vez. Acabei de aprovar o PR!!!
