### ISSUE TITLE
Sobre a recomendação de uso da voz passiva

### ISSUE THREAD

**Issue by caburu** [dcc-ufla/guia-do-tcc#2]
O guia traz a seguinte recomendação:

https://github.com/dcc-ufla/guia-do-tcc/blob/a000905dc2e0a3bfed2a5f65256fc3da1d25fca4/README.md?plain=1#L61-L70

Mas, recentemente, li recomendações para que os artigos científicos passem a evitar a voz passiva. Há várias postagens com opiniões a favor e contra, mas pelo que tenho lido a maioria dos periódicos passou a incentivar o uso da voz ativa. Algumas matérias com mais detalhes sobre essa discussão podem ser lidas [aqui](https://www.sfedit.net/active-vs-passive-voice-in-scientific-writing/) e [aqui](https://sites.duke.edu/scientificwriting/passive-voice-in-scientific-writing/).

De toda forma, não sei qual seria a realidade para os trabalhos do DCC-UFLA, já que uma das reclamações dos autores é que, apesar da mudança de orientação dos periódicos, muitos revisores continuam preferindo o uso da voz passiva (muitas vezes por hábito). Isso poderia acontecer também com os membros das bancas de TCC. Portanto, fiquei na dúvida sobre qual seria a melhor orientação para os alunos neste caso.

**Comment by paulojunior-ufla** [comment]
Ontem mesmo, lendo esse trecho, acabei pensando sobre essa questão do _uso da voz passiva_. Confesso que não tenho opinião formada sobre isso ainda. Já que, como você comentou, há argumentos de ambos os lados, o que acha de incluirmos as duas opções, por exemplo:

> [EVITE!] Nós fizemos a avaliação do aplicativo com 10 usuários...  
> [ASSIM FICA MELHOR] A avaliação do aplicativo foi realizada com 10 usuários... 
> [OU ENTÃO, ASSIM] Dez usuários realizaram a avaliação do aplicativo...

**Comment by caburu** [comment]
Seria uma opção, mas ainda tenho dúvidas. Esse exemplo cai em uma categoria bem específica, pois conseguimos uma construção impessoal mesmo usando a voz ativa. Mas, pensando em outros exemplos, o que muitos defendem é que deveríamos sim usar a primeira pessoa (eu, nós).

Enfim, minha dúvida é mais geral, se deveríamos continuar sugerindo que o texto seja impessoal ou não.

**Comment by paulojunior-ufla** [comment]
Entendi. Alguns se incomodam com frases, tais como "A Tabela X apresenta..."; para eles, a "Tabela" é algo inanimado e, portanto, ela não apresenta nada. Portanto, o correto seria "Na Tabela X, é apresentado...". Neste caso, para mim, tanto faz. 

Agora, confesso que ainda me soa estranho ler: "Nós fizemos um experimento com 10 participantes". Mas, como o intuito do guia não é ser dogmático, podemos colocar uma nota explicativa sobre essa questão. Você acha que assim fica legal?

**Comment by caburu** [comment]
Olá @paulojunior-ufla, o que acha dessa sugestão?

### 3.4. Uso da voz ativa ou voz passiva
  
Seja cuidadoso ao usar pronomes e verbos em primeira pessoa (singular ou plural). Durante muito tempo, foi praticamente consenso na comunidade científica, que os textos deveriam sempre evitar a voz passiva, pois o foco deveria estar na pesquisa e não no(s) autor(es).

Seguindo essa ideia, seria melhor, por exemplo, escrever *A avaliação do aplicativo foi realizada com 10 usuários...* do que *Nós fizemos a avaliação do aplicativo com 10 usuários...*.

Mas, recentemente, diversos veículos científicos têm incentivado o uso da voz ativa. Um dos argumentos é que a frase construída na voz ativa é mais direta e fácil de entender, o que facilita o entendimento do texto científico como um todo.

De toda forma, como isso não parece ainda ser um novo consenso, seja cuidadoso ao escolher sua forma de escrita. Uma **sugestão geral é: escolha entre voz ativa ou voz passiva de forma a manter o foco na informação que é mais importante na frase**.

**Comment by paulojunior-ufla** [comment]
Excelente, @caburu. Você poderia realizar as alterações, por favor? Obrigado por sua contribuição!
