### ISSUE TITLE
Incluir resumo no convite para membros da banca?

### ISSUE THREAD

**Issue by caburu** [dcc-ufla/guia-do-tcc#3]
Nas orientações sobre o convite de participação para os membros da banca, seria interessante sugerir aos alunos que incluam o resumo/abstract do trabalho? (talvez com anexo?)

Por um lado, pode tornar o e-mail de contado inicial mais longo. Mas, por outro, ajuda o professor a ter uma ideia do melhor do trabalho. Sugiro isso porque eu, particularmente, costumo responder os e-mails de convite pedindo aos alunos para enviarem o resumo :)

**Comment by paulojunior-ufla** [comment]
Acho super válido, @caburu. É uma ótima ideia. Se quiser alterar o texto, fique à vontade!
