### ISSUE TITLE
Objetivos

### ISSUE THREAD

**Issue by paulojunior-ufla** [dcc-ufla/guia-do-tcc#4]
Elaborar a seção que descreve os objetivos de uma [monografia](https://github.com/dcc-ufla/guia-do-tcc/blob/main/monografia.md#1-qual-%C3%A9-o-objetivo-de-uma-monografia) e de um relatório de [estágio](https://github.com/dcc-ufla/guia-do-tcc/blob/main/relatorio-estagio.md#1-qual-%C3%A9-o-objetivo-de-um-relat%C3%B3rio-de-est%C3%A1gio). Favor consultar os Projetos Pedagógicos dos Cursos BSI e BCC para embasar sua definição.

**Comment by JhoPhis** [comment]
Olá Paulo, eu (João Plínio) e o meu grupo (Luísa Maria e Arthur Hauck) alunos do curso de Sistemas de Informação da Universidade Federal de Lavras gostaria de contribuir com essa issue.

**Comment by paulojunior-ufla** [comment]
Olá, @JhoPhis. Obrigado pelo interesse. Fico aguardando seu PR.
