### ISSUE TITLE
[Relatório de Estágio] Atividades Realizadas

### ISSUE THREAD

**Issue by paulojunior-ufla** [dcc-ufla/guia-do-tcc#5]
Elaborar uma nova questão, denominada `Como posso escrever o capítulo "Atividades Realizadas" de um Relatório de Estágio?`, no arquivo `relatorio-estagio.md`. Utilize a resposta para a questão `Como posso escrever a "Fundamentação Teórica" de um Relatório de Estágio?` como um exemplo para guiar sua escrita.

**Comment by Pedro-Carvalho-Pereira** [comment]
Bom dia professor, gostaria de contribuir com essa issue, eu posso?

**Comment by paulojunior-ufla** [comment]
Olá, @Pedro-Carvalho-Pereira. Sim, fique à vontade! Obrigado pelo interesse.
